### ISSUE TITLE
division by zero

### ISSUE THREAD

**Issue by Lisa-aa** [jgroschwitz/GrAPES#5]
This error occurs on every calculation: ERROR: Division by zero!
while running python evaluate_all_categories.py -gt amr/testset -pt amr/output

**Comment by jgroschwitz** [comment]
Hi! This looks like the data wasn't loaded correctly. Your command looks like you maybe give it folder paths instead of file paths? Try using file paths instead (the gold data and the parser output you evaluate should each be in a single text file). If that doesn't help, would you mind sending me the files that you're trying to evaluate, as well as the full system output? Then I could have a look.

**Comment by Lisa-aa** [comment]
Hi, yes I could send you the files. I did give it files not paths to a folder.

**Comment by jgroschwitz** [comment]
Ah, I had a look at the files and the problem is: GrAPES only works for the AMRBank test set, but you used the dev set. So the code can't find the instances it is looking for. You will need to run the parser on the test set and give those outputs to GrAPES.

I will work on the code giving better error messages when something like this happens.

(By the way, are you Meaghan Fowlie's student? She will be able to give you access to the AMRBank test set if you don't have it already).

**Comment by Lisa-aa** [comment]
Hi,

Yes, I am Meaghan Fowlie’s student. I have the right file now. 

Thank you.

Best,

Lisa Aaldijk

 

Van: jgroschwitz ***@***.***> 
Verzonden: dinsdag 19 december 2023 14:22
Aan: jgroschwitz/GrAPES ***@***.***>
CC: Lisa-aa ***@***.***>; Author ***@***.***>
Onderwerp: Re: [jgroschwitz/GrAPES] division by zero (Issue #5)

 

Ah, I had a look at the files and the problem is: GrAPES only works for the AMRBank test set, but you used the dev set. So the code can't find the instances it is looking for. You will need to run the parser on the test set and give those outputs to GrAPES.

I will work on the code giving better error messages when something like this happens.

(By the way, are you Meaghan Fowlie's student? She will be able to give you access to the AMRBank test set if you don't have it already).
